// This file is auto-generated by cyMemProfiler
// Version: 0.1

#include <stdio.h>
#include <stdlib.h>
#include "instProf.h"



typedef struct {
    int x;
    int y;
} Point;

void print_point(Point *p) {
    logInstScopeEnter(0);

    printf("Point: (%d, %d)\n", p->x, p->y);

    logInstScopeExit(0);
}

void initialize_point(Point *p, int x, int y) {
    logInstScopeEnter(1);

    p->x = x;
    p->y = y;

    logInstScopeExit(1);
}

void modify_point(Point *p, int dx, int dy) {
    logInstScopeEnter(2);

    p->x += dx;
    p->y += dy;

    logInstScopeExit(2);
}

int *initialize_array(int size) {
    logInstScopeEnter(3);

    int *arr = (int *)malloc(size * sizeof(int));
    for (int i = 0; i < size; i++) {
        logInstScopeEnter(4);

        arr[i] = i;

        logInstScopeExit(4);
    }

    logInstReturn();
    return arr;

    logInstScopeExit(3);
}

void print_array(int *arr, int size) {
    logInstScopeEnter(5);

    printf("Array: ");
    for (int i = 0; i < size; i++) {
        logInstScopeEnter(6);

        printf("%d ", arr[i]);

        logInstScopeExit(6);
    }
    printf("\n");

    logInstScopeExit(5);
}

int main() {
    // Injected at-exit function for exporting and freeing data runtime data
    if (atexit(instAtExitFunc) != 0) {
        fprintf(stderr, "cyMemProfiler: Failed to register the exit function.");
        return 1;
    }

    // Init instruction counting module
    base_check();

    logInstScopeEnter(7);


    int *arr = initialize_array(5);


    print_array(arr, 5);


    arr = (int *)realloc(arr, 10 * sizeof(int));


    for (int i = 5; i < 10; i++) {
        logInstScopeEnter(8);

        arr[i] = i;

        logInstScopeExit(8);
    }


    print_array(arr, 10);


    Point *p = (Point *)malloc(sizeof(Point));


    initialize_point(p, 10, 20);


    print_point(p);


    modify_point(p, 5, -10);


    print_point(p);


    free(arr);
    free(p);


    logInstReturn();
    return 0;

    logInstScopeExit(7);
}